/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package name;

import java.util.Map;
import java.util.HashMap;

/**
 *
 * @author eeccm
 */
public class name extends javax.swing.JFrame {

    /**
     * Creates new form name
     */
    public name() {
        initComponents();
        speechBallonGuess.setText("<html>Can you guess the first letter of my name?<br>Clue: It changes everytime you click the button!<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clickButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        correctWrong = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        vowelSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        speechBallonGuess = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clickButton.setText("I want to guess");
        clickButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clickButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        correctWrong.setText("Right!Congrats");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(correctWrong)
                .addGap(0, 195, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(correctWrong)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 451, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1389, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 11, -1, -1));

        vowelSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"A", "E", "I", "O", "U"}));
        getContentPane().add(vowelSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 219, 67, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/smallandpng.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        speechBallonGuess.setText("-");
        speechBallonGuess.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(speechBallonGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 130, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hiclipart.com (2).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 196, -1));

        setBounds(0, 0, 505, 398);
    }// </editor-fold>//GEN-END:initComponents

    private void clickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickButtonActionPerformed
        // TODO add your handling code here:
        int randomValue = (int) (1 + Math.random() * (16-1));
        Map<String, String> map = new HashMap<>();
        map.put("1", "Ashley");
        map.put("2", "Elizabeth");
        map.put("3", "Ichika");
        map.put("4", "Olivia");
        map.put("5", "Ulyana");
        map.put("6", "Amy");
        map.put("7", "Emma");
        map.put("8", "Iminathi");
        map.put("9", "Olga");
        map.put("10", "Ula");
        map.put("11", "Ana");
        map.put("12", "Emily");
        map.put("13", "Irene");
        map.put("14", "Ophelia");
        map.put("15", "Ursula");
        String randomName = map.get((Integer.toString(randomValue)));
        char vowel = randomName.charAt(0);
        String stringVowel = Character.toString(vowel);
        System.out.println(vowel);
        String chooseVowel = (String) vowelSpinner.getValue();
        System.out.println(chooseVowel);
        String correctVowel = (chooseVowel.equals(stringVowel))?"<html>Correct! My name now is<html> "+ randomName:"<html>Wrong,my name now is<html> "+ randomName;
        System.out.println(correctVowel);
        speechBallonGuess.setText(correctVowel);
    }//GEN-LAST:event_clickButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new name().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clickButton;
    private javax.swing.JLabel correctWrong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel speechBallonGuess;
    private javax.swing.JSpinner vowelSpinner;
    // End of variables declaration//GEN-END:variables
}
